service: stripe-payment-processor

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

  apiKeys:
    - apiKey

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: post
          private: true
          cors: true
